version: '3.9'
services:
  master:
    image: mysql:8.0
    container_name: mysql_master
    environment:
      MYSQL_ROOT_PASSWORD: Admin@123
      MYSQL_DATABASE: test
      MYSQL_REPLICATION_USER: repl
      MYSQL_REPLICATION_PASSWORD: Repl@123
    ports:
      - 3307:3306
    volumes:
      - ./master-conf:/etc/mysql/conf.d
      - ./master-data:/var/lib/mysql
      - ./master-conf/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mysql_net
  
  slave:
    image: mysql:8.0
    container_name: mysql_slave
    environment:
      MYSQL_ROOT_PASSWORD: Admin@123
      MYSQL_DATABASE: test
      MYSQL_REPLICATION_USER: repl
      MYSQL_REPLICATION_PASSWORD: Repl@123
    ports:
      - 3308:3306
    volumes:
      - ./slave-conf:/etc/mysql/conf.d
      - ./slave-data:/var/lib/mysql
      - ./slave-conf/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mysql_net
    depends_on:
      - master

networks:
  mysql_net:
    driver: bridge